FROM node:alpine

ENV CHOKIDAR_USEPOLLING=1

RUN mkdir /source
WORKDIR /source

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install

VOLUME /source/node_modules

COPY elm.json elm.json
COPY src src

# To install elm packages
RUN npm run build:elm; exit 0

VOLUME /source/elm-stuff
VOLUME /root/.elm

ENTRYPOINT ["sh", "entrypoint.elm.sh"]
